import type {
  BookshelfItem,
  BookshelfResponse,
  ChapterContent,
  ChapterListResponse,
  ChapterSummary,
  ItemsListResponse,
  MembershipOverview,
  NovelCard,
  NovelDetail,
  NovelListResponse,
  PurchaseMembershipRequest,
  ReadingProgress,
  RelatedNovelSummary,
} from "@minix/contracts";

import type { UserState } from "./types";
import { buildSampleCoverAssetPath } from "./sample-assets";

export const HOST_ITEMS: ItemsListResponse["items"] = [
  {
    id: "lesson_1",
    title: "Warm-up Vocabulary",
    subtitle: "8 travel words for airport check-in and hotel arrival",
    categoryLabel: "Warm-up",
    difficultyLabel: "A2",
    recommendedReason: "Start here to unlock the core words used by the rest of today's lesson.",
    durationMinutes: 2,
  },
  {
    id: "lesson_2",
    title: "Input Dialogue",
    subtitle: "Read a short airport check-in exchange and notice the key phrases",
    categoryLabel: "Input",
    difficultyLabel: "A2",
    recommendedReason: "Use the new vocabulary inside a real mini-dialogue before moving into active practice.",
    durationMinutes: 2,
  },
  {
    id: "lesson_3",
    title: "Guided Practice",
    subtitle: "Rebuild 3 short travel sentences with the lesson phrases",
    categoryLabel: "Practice",
    difficultyLabel: "A2-B1",
    recommendedReason: "This step turns passive input into active recall before you start speaking.",
    durationMinutes: 2,
  },
  {
    id: "lesson_4",
    title: "Speak Out Loud",
    subtitle: "Repeat 5 travel lines and practice natural rhythm out loud",
    categoryLabel: "Speaking",
    difficultyLabel: "B1",
    recommendedReason: "Now turn the lesson into spoken output while the sentence patterns are still fresh.",
    durationMinutes: 2,
  },
  {
    id: "lesson_5",
    title: "Wrap-up Review",
    subtitle: "Fix 2 mistakes, review the key phrase, and close the lesson cleanly",
    categoryLabel: "Wrap-up",
    difficultyLabel: "A2",
    recommendedReason: "Finish here so the lesson ends with one clear correction and one reusable phrase.",
    durationMinutes: 1,
  },
];

export const DEFAULT_BOOKSHELF_NOVEL_IDS = ["novel_lantern", "novel_brocade"] as const;

export const DEFAULT_PROGRESS_BY_NOVEL_ID: Record<string, ReadingProgress> = {
  novel_lantern: {
    novelId: "novel_lantern",
    chapterId: "lantern_ch_03",
    chapterTitle: "Chapter 3 · Witness On The Water",
    progressPercent: 0.46,
    updatedAt: "2026-03-22T08:00:00.000Z",
  },
  novel_brocade: {
    novelId: "novel_brocade",
    chapterId: "brocade_ch_04",
    chapterTitle: "Chapter 4 · The Final Stitch",
    progressPercent: 1,
    updatedAt: "2026-03-12T08:00:00.000Z",
  },
};

export const DEFAULT_MEMBERSHIP_OVERVIEW: MembershipOverview = {
  active: false,
  tier: "signed-in",
  entitlementScope: "none",
  statusLabel: "Signed in with standard reading access",
  renewalLabel: "Upgrade to unlock full serialized reading",
  headline: "Membership Center",
  subheadline: "Unlock paid chapters, long-form serials, and cleaner continuation across devices.",
  benefits: [
    {
      key: "locked-chapters",
      label: "Locked Chapter Access",
      description: "Open chapters that sit behind the free and trial boundary.",
    },
    {
      key: "full-serials",
      label: "Full Serial Access",
      description: "Continue reading on premium or membership-only titles without interruption.",
    },
    {
      key: "priority-updates",
      label: "Priority Updates",
      description: "Keep reading progress and update cues aligned across the shelf and reader.",
    },
  ],
};

export const MEMBER_RENEWAL_LABELS: Record<PurchaseMembershipRequest["planId"], string> = {
  monthly: "Monthly plan active",
  quarterly: "Quarterly plan active",
  annual: "Annual plan active",
};

export const NOVELS: NovelDetail[] = [
  {
    id: "novel_lantern",
    slug: "ashes-of-the-lantern",
    title: "Ashes Of The Lantern",
    subtitle: "A slow-burn mystery inside a rain-soaked canal city",
    author: {
      id: "author_lin",
      name: "Lin Yue",
      bio: "Writes atmospheric mysteries about memory, ritual, and cities that refuse to sleep.",
    },
    coverUrl: buildSampleCoverAssetPath("novel-lantern"),
    summary:
      "When an archivist inherits a forbidden lantern that reveals hidden rooms in the city, every glow uncovers another debt, another missing witness, and another chapter of a murder the canal district tried to drown.",
    categoryKey: "mystery",
    categoryLabel: "Mystery",
    tags: [
      { key: "serial", label: "Serial" },
      { key: "noir", label: "Noir" },
      { key: "slow-burn", label: "Slow Burn" },
    ],
    status: "serializing",
    wordCount: 182000,
    chapterCount: 6,
    readingCount: 22840,
    bookshelfCount: 6240,
    ratingScore: 4.8,
    ratingCount: 6320,
    favoriteCount: 18420,
    updateCadenceLabel: "Updates twice weekly on Tuesday and Friday",
    updateHistoryLabel:
      "The last three chapters landed across four days, so the mystery arc still feels hot and current.",
    trialRuleLabel: "Open access title with uninterrupted reading across the current serial run",
    accessRuleSummaryLabel:
      "No membership wall interrupts the current serial route, so the strongest choice here is simply whether to continue now or shelf it for tonight.",
    authorPresenceLabel:
      "Lin Yue's mysteries are known for ritual clues, soaked city atmospheres, and chapters that always end one revelation too early.",
    relatedLaneLabel:
      "Readers who stay for ritual noir and city memory usually move next into merchant mysteries or prestige court intrigue.",
    latestChapter: {
      id: "lantern_ch_06",
      title: "Chapter 6 · The Ember Ledger",
      order: 6,
      updatedAt: "2026-03-22T08:00:00.000Z",
    },
    firstChapterId: "lantern_ch_01",
    continueChapterId: "lantern_ch_03",
    isFree: true,
    isTrial: true,
    requiresMembership: false,
    isPurchased: true,
  },
  {
    id: "novel_brocade",
    slug: "brocade-pavilion",
    title: "Brocade Pavilion",
    subtitle: "Court intrigue woven through silk, debt, and inherited names",
    author: {
      id: "author_qiao",
      name: "Qiao An",
      bio: "Known for palace dramas with sharp dialogue and tightly wound emotional stakes.",
    },
    coverUrl: buildSampleCoverAssetPath("novel-brocade"),
    summary:
      "A forgotten daughter is summoned back to the capital to manage the family pavilion, only to discover the embroidery ledgers hide bribes, coded confessions, and a succession war no one dares to say aloud.",
    categoryKey: "fantasy",
    categoryLabel: "Fantasy",
    tags: [
      { key: "court", label: "Court Politics" },
      { key: "romance", label: "Romance" },
      { key: "completed", label: "Completed" },
    ],
    status: "completed",
    wordCount: 264000,
    chapterCount: 4,
    readingCount: 45120,
    bookshelfCount: 10300,
    ratingScore: 4.9,
    ratingCount: 9810,
    favoriteCount: 22640,
    updateCadenceLabel: "Completed run with full archive access for members",
    updateHistoryLabel:
      "The archive is complete, which means every chapter handoff now reads as a clean unlock proposition instead of a moving serial schedule.",
    trialRuleLabel: "Trial opens the first two chapters before the membership boundary locks the full run",
    accessRuleSummaryLabel:
      "The trial is generous enough to prove tone and stakes, but the decisive unlock moment arrives as soon as the court ledger plot fully opens.",
    authorPresenceLabel:
      "Qiao An's court dramas sell on sharp dialogue, inheritance pressure, and emotional reversals that keep every chapter feeling expensive.",
    relatedLaneLabel:
      "Readers who convert on premium court drama often cross into archive fantasy and other titles with strong household politics.",
    latestChapter: {
      id: "brocade_ch_04",
      title: "Chapter 4 · The Final Stitch",
      order: 4,
      updatedAt: "2026-03-12T08:00:00.000Z",
    },
    firstChapterId: "brocade_ch_01",
    continueChapterId: "brocade_ch_02",
    isFree: false,
    isTrial: true,
    requiresMembership: true,
    isPurchased: false,
  },
  {
    id: "novel_sword",
    slug: "sword-before-dawn",
    title: "Sword Before Dawn",
    subtitle: "A road novel about sect rivalries and one impossible oath",
    author: {
      id: "author_shen",
      name: "Shen Mo",
      bio: "Builds martial worlds that feel intimate first and epic second.",
    },
    coverUrl: buildSampleCoverAssetPath("novel-sword"),
    summary:
      "After breaking his sect's final commandment, a swordsman escorts a witness across three provinces while every school along the road decides whether to collect the bounty or hear the truth.",
    categoryKey: "wuxia",
    categoryLabel: "Wuxia",
    tags: [
      { key: "journey", label: "Journey" },
      { key: "sects", label: "Sect Conflict" },
    ],
    status: "serializing",
    wordCount: 138000,
    chapterCount: 5,
    readingCount: 18540,
    bookshelfCount: 4910,
    ratingScore: 4.6,
    ratingCount: 4010,
    favoriteCount: 12110,
    updateCadenceLabel: "Weekly Saturday update cadence",
    updateHistoryLabel:
      "A steadier weekly rhythm makes this title feel dependable, with update expectations that suit long-road reading habits.",
    trialRuleLabel: "Open access serial with no membership boundary on the current route",
    accessRuleSummaryLabel:
      "Open access keeps the path clean here, so the detail page's job is mostly to reinforce trust in cadence and continuation.",
    authorPresenceLabel:
      "Shen Mo writes martial travelogues that feel intimate before they scale outward, which keeps the road-story pitch grounded.",
    relatedLaneLabel:
      "Readers who stay for oath-driven journeys usually continue into slower serials with a strong witness or investigation spine.",
    latestChapter: {
      id: "sword_ch_05",
      title: "Chapter 5 · Under The Watchtower",
      order: 5,
      updatedAt: "2026-03-21T08:00:00.000Z",
    },
    firstChapterId: "sword_ch_01",
    continueChapterId: "sword_ch_02",
    isFree: true,
    isTrial: false,
    requiresMembership: false,
    isPurchased: true,
  },
  {
    id: "novel_orchid",
    slug: "orchid-ledger",
    title: "Orchid Ledger",
    subtitle: "Merchant intrigue, river guilds, and a ledger that outlives its owners",
    author: {
      id: "author_ji",
      name: "Ji Wen",
      bio: "Writes mercantile epics built on debt, loyalty, and the weight of inherited cities.",
    },
    coverUrl: buildSampleCoverAssetPath("novel-orchid"),
    summary:
      "After a warehouse fire wipes out the river market's records, a junior clerk discovers one orchid-stamped ledger survived. Every page points to a shipment that never arrived and a guild elder who was never supposed to die.",
    categoryKey: "mystery",
    categoryLabel: "Mystery",
    tags: [
      { key: "guilds", label: "Guild Politics" },
      { key: "merchant", label: "Merchant Drama" },
      { key: "slow", label: "Slow Build" },
    ],
    status: "serializing",
    wordCount: 206000,
    chapterCount: 3,
    readingCount: 17420,
    bookshelfCount: 4130,
    ratingScore: 4.7,
    ratingCount: 3580,
    favoriteCount: 10920,
    updateCadenceLabel: "New chapters land whenever the guild ledger arc resolves",
    updateHistoryLabel:
      "Recent chapter drops cluster around major ledger reveals, so update timing feels event-driven instead of weekly routine.",
    trialRuleLabel: "Trial-enabled mystery with open continuation through the current chapter list",
    accessRuleSummaryLabel:
      "Trial remains open on the current route, so this title behaves like a low-friction conversion from curiosity into shelf intent.",
    authorPresenceLabel:
      "Ji Wen leans into merchant pressure, civic scale, and procedural clue trails that reward readers who like systems as much as drama.",
    relatedLaneLabel:
      "Readers who click into merchant mysteries tend to keep browsing adjacent guild, archive, and prestige intrigue titles.",
    latestChapter: {
      id: "orchid_ch_03",
      title: "Chapter 3 · The Missing Seal",
      order: 3,
      updatedAt: "2026-03-23T08:00:00.000Z",
    },
    firstChapterId: "orchid_ch_01",
    continueChapterId: "orchid_ch_02",
    isFree: true,
    isTrial: true,
    requiresMembership: false,
    isPurchased: true,
  },
  {
    id: "novel_glass",
    slug: "glass-harbor",
    title: "Glass Harbor",
    subtitle: "A paused coastal fantasy with saints, tariffs, and weather cults",
    author: {
      id: "author_rao",
      name: "Rao Yin",
      bio: "Blends luminous settings with political fantasy and strong episodic arcs.",
    },
    coverUrl: buildSampleCoverAssetPath("novel-glass"),
    summary:
      "At the edge of a harbor where weather can be bought and sold, a customs translator finds a shrine register naming ships that sank years before their captains were born.",
    categoryKey: "fantasy",
    categoryLabel: "Fantasy",
    tags: [
      { key: "harbor", label: "Harbor City" },
      { key: "paused", label: "Paused Run" },
      { key: "premium", label: "Premium" },
    ],
    status: "paused",
    wordCount: 149000,
    chapterCount: 3,
    readingCount: 13240,
    bookshelfCount: 2975,
    ratingScore: 4.5,
    ratingCount: 2890,
    favoriteCount: 8740,
    updateCadenceLabel: "Paused title with archive maintenance and occasional premium bonus notes",
    updateHistoryLabel:
      "Because the run is paused, update history matters more than cadence: readers need to know this is an archive with occasional movement, not an abandoned listing.",
    trialRuleLabel: "Trial preview covers the opening chapter before premium continuation begins",
    accessRuleSummaryLabel:
      "The opening trial exists to sell atmosphere first, then let premium continuation carry the paused archive for committed readers.",
    authorPresenceLabel:
      "Rao Yin's coastal fantasies trade on luminous settings and political weather systems, which makes the pause status part of the dossier story.",
    relatedLaneLabel:
      "Readers who still buy into paused premium worlds often browse for adjacent fantasy archives with strong setting-first appeal.",
    latestChapter: {
      id: "glass_ch_03",
      title: "Chapter 3 · Tariff For Rain",
      order: 3,
      updatedAt: "2026-03-09T08:00:00.000Z",
    },
    firstChapterId: "glass_ch_01",
    continueChapterId: "glass_ch_01",
    isFree: false,
    isTrial: true,
    requiresMembership: true,
    isPurchased: false,
  },
];

export const CHAPTER_LISTS: Record<string, ChapterListResponse> = {
  novel_lantern: {
    novelId: "novel_lantern",
    totalChapters: 6,
    continueChapterId: "lantern_ch_03",
    volumes: [
      {
        id: "lantern_vol_01",
        novelId: "novel_lantern",
        title: "Volume I · Rain Archive",
        order: 1,
        chapters: [
          {
            id: "lantern_ch_01",
            novelId: "novel_lantern",
            volumeId: "lantern_vol_01",
            title: "Chapter 1 · The Closed Stack",
            order: 1,
            wordCount: 4200,
            updatedAt: "2026-03-18T08:00:00.000Z",
            isFree: true,
            isTrial: true,
            requiresMembership: false,
            isPurchased: true,
          },
          {
            id: "lantern_ch_02",
            novelId: "novel_lantern",
            volumeId: "lantern_vol_01",
            title: "Chapter 2 · A Door Behind Smoke",
            order: 2,
            wordCount: 4380,
            updatedAt: "2026-03-19T08:00:00.000Z",
            isFree: true,
            isTrial: true,
            requiresMembership: false,
            isPurchased: true,
          },
          {
            id: "lantern_ch_03",
            novelId: "novel_lantern",
            volumeId: "lantern_vol_01",
            title: "Chapter 3 · Witness On The Water",
            order: 3,
            wordCount: 4510,
            updatedAt: "2026-03-20T08:00:00.000Z",
            isFree: true,
            isTrial: true,
            requiresMembership: false,
            isPurchased: true,
          },
        ],
      },
      {
        id: "lantern_vol_02",
        novelId: "novel_lantern",
        title: "Volume II · Heat Signature",
        order: 2,
        chapters: [
          {
            id: "lantern_ch_04",
            novelId: "novel_lantern",
            volumeId: "lantern_vol_02",
            title: "Chapter 4 · The Narrow Courtyard",
            order: 4,
            wordCount: 4630,
            updatedAt: "2026-03-21T08:00:00.000Z",
            isFree: true,
            isTrial: true,
            requiresMembership: false,
            isPurchased: true,
          },
          {
            id: "lantern_ch_05",
            novelId: "novel_lantern",
            volumeId: "lantern_vol_02",
            title: "Chapter 5 · Ink On Wet Stone",
            order: 5,
            wordCount: 4720,
            updatedAt: "2026-03-21T12:00:00.000Z",
            isFree: true,
            isTrial: true,
            requiresMembership: false,
            isPurchased: true,
          },
          {
            id: "lantern_ch_06",
            novelId: "novel_lantern",
            volumeId: "lantern_vol_02",
            title: "Chapter 6 · The Ember Ledger",
            order: 6,
            wordCount: 4880,
            updatedAt: "2026-03-22T08:00:00.000Z",
            isFree: true,
            isTrial: true,
            requiresMembership: false,
            isPurchased: true,
          },
        ],
      },
    ],
  },
  novel_brocade: {
    novelId: "novel_brocade",
    totalChapters: 4,
    continueChapterId: "brocade_ch_02",
    volumes: [
      {
        id: "brocade_vol_01",
        novelId: "novel_brocade",
        title: "Volume I · Capital Thread",
        order: 1,
        chapters: [
          {
            id: "brocade_ch_01",
            novelId: "novel_brocade",
            volumeId: "brocade_vol_01",
            title: "Chapter 1 · Return To The Pavilion",
            order: 1,
            wordCount: 5180,
            updatedAt: "2026-03-10T08:00:00.000Z",
            isFree: false,
            isTrial: true,
            requiresMembership: true,
            isPurchased: false,
          },
          {
            id: "brocade_ch_02",
            novelId: "novel_brocade",
            volumeId: "brocade_vol_01",
            title: "Chapter 2 · Gold Thread Accounts",
            order: 2,
            wordCount: 5260,
            updatedAt: "2026-03-10T12:00:00.000Z",
            isFree: false,
            isTrial: true,
            requiresMembership: true,
            isPurchased: false,
          },
          {
            id: "brocade_ch_03",
            novelId: "novel_brocade",
            volumeId: "brocade_vol_01",
            title: "Chapter 3 · The Unnamed Seal",
            order: 3,
            wordCount: 5340,
            updatedAt: "2026-03-11T08:00:00.000Z",
            isFree: false,
            isTrial: false,
            requiresMembership: true,
            isPurchased: false,
          },
          {
            id: "brocade_ch_04",
            novelId: "novel_brocade",
            volumeId: "brocade_vol_01",
            title: "Chapter 4 · The Final Stitch",
            order: 4,
            wordCount: 5420,
            updatedAt: "2026-03-12T08:00:00.000Z",
            isFree: false,
            isTrial: false,
            requiresMembership: true,
            isPurchased: false,
          },
        ],
      },
    ],
  },
  novel_sword: {
    novelId: "novel_sword",
    totalChapters: 5,
    continueChapterId: "sword_ch_02",
    volumes: [
      {
        id: "sword_vol_01",
        novelId: "novel_sword",
        title: "Volume I · Road Oath",
        order: 1,
        chapters: [
          {
            id: "sword_ch_01",
            novelId: "novel_sword",
            volumeId: "sword_vol_01",
            title: "Chapter 1 · Frost On The Ferry",
            order: 1,
            wordCount: 4010,
            updatedAt: "2026-03-17T08:00:00.000Z",
            isFree: true,
            isTrial: false,
            requiresMembership: false,
            isPurchased: true,
          },
          {
            id: "sword_ch_02",
            novelId: "novel_sword",
            volumeId: "sword_vol_01",
            title: "Chapter 2 · The Salt Merchant's Son",
            order: 2,
            wordCount: 4160,
            updatedAt: "2026-03-18T08:00:00.000Z",
            isFree: true,
            isTrial: false,
            requiresMembership: false,
            isPurchased: true,
          },
          {
            id: "sword_ch_03",
            novelId: "novel_sword",
            volumeId: "sword_vol_01",
            title: "Chapter 3 · Wind Over The Shrine",
            order: 3,
            wordCount: 4230,
            updatedAt: "2026-03-19T08:00:00.000Z",
            isFree: true,
            isTrial: false,
            requiresMembership: false,
            isPurchased: true,
          },
          {
            id: "sword_ch_04",
            novelId: "novel_sword",
            volumeId: "sword_vol_01",
            title: "Chapter 4 · Three Schools Waiting",
            order: 4,
            wordCount: 4380,
            updatedAt: "2026-03-20T08:00:00.000Z",
            isFree: true,
            isTrial: false,
            requiresMembership: false,
            isPurchased: true,
          },
          {
            id: "sword_ch_05",
            novelId: "novel_sword",
            volumeId: "sword_vol_01",
            title: "Chapter 5 · Under The Watchtower",
            order: 5,
            wordCount: 4460,
            updatedAt: "2026-03-21T08:00:00.000Z",
            isFree: true,
            isTrial: false,
            requiresMembership: false,
            isPurchased: true,
          },
        ],
      },
    ],
  },
  novel_orchid: {
    novelId: "novel_orchid",
    totalChapters: 3,
    continueChapterId: "orchid_ch_02",
    volumes: [
      {
        id: "orchid_vol_01",
        novelId: "novel_orchid",
        title: "Volume I · River Freight",
        order: 1,
        chapters: [
          {
            id: "orchid_ch_01",
            novelId: "novel_orchid",
            volumeId: "orchid_vol_01",
            title: "Chapter 1 · Ash In The Warehouse",
            order: 1,
            wordCount: 4670,
            updatedAt: "2026-03-21T08:00:00.000Z",
            isFree: true,
            isTrial: true,
            requiresMembership: false,
            isPurchased: true,
          },
          {
            id: "orchid_ch_02",
            novelId: "novel_orchid",
            volumeId: "orchid_vol_01",
            title: "Chapter 2 · Freight Without Witness",
            order: 2,
            wordCount: 4790,
            updatedAt: "2026-03-22T08:00:00.000Z",
            isFree: true,
            isTrial: true,
            requiresMembership: false,
            isPurchased: true,
          },
          {
            id: "orchid_ch_03",
            novelId: "novel_orchid",
            volumeId: "orchid_vol_01",
            title: "Chapter 3 · The Missing Seal",
            order: 3,
            wordCount: 4930,
            updatedAt: "2026-03-23T08:00:00.000Z",
            isFree: true,
            isTrial: true,
            requiresMembership: false,
            isPurchased: true,
          },
        ],
      },
    ],
  },
  novel_glass: {
    novelId: "novel_glass",
    totalChapters: 3,
    continueChapterId: "glass_ch_01",
    volumes: [
      {
        id: "glass_vol_01",
        novelId: "novel_glass",
        title: "Volume I · Weather Port",
        order: 1,
        chapters: [
          {
            id: "glass_ch_01",
            novelId: "novel_glass",
            volumeId: "glass_vol_01",
            title: "Chapter 1 · Customs Bell",
            order: 1,
            wordCount: 4510,
            updatedAt: "2026-03-07T08:00:00.000Z",
            isFree: false,
            isTrial: true,
            requiresMembership: true,
            isPurchased: false,
          },
          {
            id: "glass_ch_02",
            novelId: "novel_glass",
            volumeId: "glass_vol_01",
            title: "Chapter 2 · Ledger Of Tides",
            order: 2,
            wordCount: 4630,
            updatedAt: "2026-03-08T08:00:00.000Z",
            isFree: false,
            isTrial: true,
            requiresMembership: true,
            isPurchased: false,
          },
          {
            id: "glass_ch_03",
            novelId: "novel_glass",
            volumeId: "glass_vol_01",
            title: "Chapter 3 · Tariff For Rain",
            order: 3,
            wordCount: 4760,
            updatedAt: "2026-03-09T08:00:00.000Z",
            isFree: false,
            isTrial: false,
            requiresMembership: true,
            isPurchased: false,
          },
        ],
      },
    ],
  },
};

export const CHAPTER_CONTENT: Record<string, ChapterContent> = {
  lantern_ch_01: {
    id: "lantern_ch_01",
    novelId: "novel_lantern",
    title: "Chapter 1 · The Closed Stack",
    order: 1,
    wordCount: 4200,
    updatedAt: "2026-03-18T08:00:00.000Z",
    nav: { nextChapterId: "lantern_ch_02" },
    isFree: true,
    isTrial: true,
    requiresMembership: false,
    isPurchased: true,
    content:
      "Rain moved through the canal city like a second archive.\n\nEvery ledger swelled at the edges, every rope bridge remembered a different weight, and every closed room collected the smell of ash before dawn.\n\nWhen Yan Luo opened the inherited lantern, the wall beside the closed stack did not crumble. It simply admitted it had always been a door.",
  },
  lantern_ch_02: {
    id: "lantern_ch_02",
    novelId: "novel_lantern",
    title: "Chapter 2 · A Door Behind Smoke",
    order: 2,
    wordCount: 4380,
    updatedAt: "2026-03-19T08:00:00.000Z",
    nav: { previousChapterId: "lantern_ch_01", nextChapterId: "lantern_ch_03" },
    isFree: true,
    isTrial: true,
    requiresMembership: false,
    isPurchased: true,
    content:
      "The room behind the wall contained no treasure.\n\nIt held a table, a cup gone cold, and a witness statement someone had tried to erase with steam.\n\nThe signature remained. The date did not.",
  },
  lantern_ch_03: {
    id: "lantern_ch_03",
    novelId: "novel_lantern",
    title: "Chapter 3 · Witness On The Water",
    order: 3,
    wordCount: 4510,
    updatedAt: "2026-03-20T08:00:00.000Z",
    nav: { previousChapterId: "lantern_ch_02", nextChapterId: "lantern_ch_04" },
    isFree: true,
    isTrial: true,
    requiresMembership: false,
    isPurchased: true,
    content:
      "A woman waited on the mooring steps with one shoe in her hand and canal mud on her sleeve.\n\nShe said she had seen the body three nights before the city claimed it existed.\n\nShe said the lantern had already been lit.",
  },
  lantern_ch_04: {
    id: "lantern_ch_04",
    novelId: "novel_lantern",
    title: "Chapter 4 · The Narrow Courtyard",
    order: 4,
    wordCount: 4630,
    updatedAt: "2026-03-21T08:00:00.000Z",
    nav: { previousChapterId: "lantern_ch_03", nextChapterId: "lantern_ch_05" },
    isFree: true,
    isTrial: true,
    requiresMembership: false,
    isPurchased: true,
    content:
      "The courtyard could only be reached when the lantern dimmed.\n\nEvery brick carried a different family mark, as if the city had built the place from confiscated homes.\n\nThere, between drainage stones, Yan Luo found the first ember ledger.",
  },
  lantern_ch_05: {
    id: "lantern_ch_05",
    novelId: "novel_lantern",
    title: "Chapter 5 · Ink On Wet Stone",
    order: 5,
    wordCount: 4720,
    updatedAt: "2026-03-21T12:00:00.000Z",
    nav: { previousChapterId: "lantern_ch_04", nextChapterId: "lantern_ch_06" },
    isFree: true,
    isTrial: true,
    requiresMembership: false,
    isPurchased: true,
    content:
      "The ledger was written in ordinary commerce codes, but the totals made no sense.\n\nNo district ordered that much lamp oil in flood season.\n\nNo district admitted buying fire after midnight at all.",
  },
  lantern_ch_06: {
    id: "lantern_ch_06",
    novelId: "novel_lantern",
    title: "Chapter 6 · The Ember Ledger",
    order: 6,
    wordCount: 4880,
    updatedAt: "2026-03-22T08:00:00.000Z",
    nav: { previousChapterId: "lantern_ch_05" },
    isFree: true,
    isTrial: true,
    requiresMembership: false,
    isPurchased: true,
    content:
      "Every name in the ledger belonged to someone officially dead.\n\nSome had drowned. Some had disappeared. One had signed the archivist's inheritance order.\n\nYan Luo closed the lantern only when the paper beneath it began to glow back.",
  },
  brocade_ch_01: {
    id: "brocade_ch_01",
    novelId: "novel_brocade",
    title: "Chapter 1 · Return To The Pavilion",
    order: 1,
    wordCount: 5180,
    updatedAt: "2026-03-10T08:00:00.000Z",
    nav: { nextChapterId: "brocade_ch_02" },
    isFree: false,
    isTrial: true,
    requiresMembership: true,
    isPurchased: false,
    trialEndOffset: 520,
    content:
      "No one in the capital welcomed a daughter who had already been written out of the family genealogy.\n\nBut the accounts welcomed her less.\n\nEvery silk roll in Brocade Pavilion had been sold twice.",
  },
  brocade_ch_02: {
    id: "brocade_ch_02",
    novelId: "novel_brocade",
    title: "Chapter 2 · Gold Thread Accounts",
    order: 2,
    wordCount: 5260,
    updatedAt: "2026-03-10T12:00:00.000Z",
    nav: { previousChapterId: "brocade_ch_01", nextChapterId: "brocade_ch_03" },
    isFree: false,
    isTrial: true,
    requiresMembership: true,
    isPurchased: false,
    trialEndOffset: 460,
    content:
      "The fake ledgers were beautiful.\n\nMargins gilded, errors symmetrical, each lie balanced with the elegance of a wedding sleeve.\n\nWhoever forged them expected admiration before suspicion.",
  },
  brocade_ch_03: {
    id: "brocade_ch_03",
    novelId: "novel_brocade",
    title: "Chapter 3 · The Unnamed Seal",
    order: 3,
    wordCount: 5340,
    updatedAt: "2026-03-11T08:00:00.000Z",
    nav: { previousChapterId: "brocade_ch_02", nextChapterId: "brocade_ch_04" },
    isFree: false,
    isTrial: false,
    requiresMembership: true,
    isPurchased: false,
    content:
      "Behind the third drawer lay a wax seal without a household mark.\n\nIn the capital, anonymity was more dangerous than accusation.\n\nIt meant the order came from above the family tree.",
  },
  brocade_ch_04: {
    id: "brocade_ch_04",
    novelId: "novel_brocade",
    title: "Chapter 4 · The Final Stitch",
    order: 4,
    wordCount: 5420,
    updatedAt: "2026-03-12T08:00:00.000Z",
    nav: { previousChapterId: "brocade_ch_03" },
    isFree: false,
    isTrial: false,
    requiresMembership: true,
    isPurchased: false,
    content:
      "The last robe on the stand was unfinished only at the collar.\n\nA single red thread waited there, enough to save the design or ruin the wearer.\n\nShe left the needle where anyone with rank could see it.",
  },
  sword_ch_01: {
    id: "sword_ch_01",
    novelId: "novel_sword",
    title: "Chapter 1 · Frost On The Ferry",
    order: 1,
    wordCount: 4010,
    updatedAt: "2026-03-17T08:00:00.000Z",
    nav: { nextChapterId: "sword_ch_02" },
    isFree: true,
    isTrial: false,
    requiresMembership: false,
    isPurchased: true,
    content:
      "By dawn the ferry ropes had frozen stiff enough to sing.\n\nLu Shen stood on the deck with one hand on his scabbard and one eye on the witness who had not slept.\n\nThe bounty notices had reached the river before they had.",
  },
  sword_ch_02: {
    id: "sword_ch_02",
    novelId: "novel_sword",
    title: "Chapter 2 · The Salt Merchant's Son",
    order: 2,
    wordCount: 4160,
    updatedAt: "2026-03-18T08:00:00.000Z",
    nav: { previousChapterId: "sword_ch_01", nextChapterId: "sword_ch_03" },
    isFree: true,
    isTrial: false,
    requiresMembership: false,
    isPurchased: true,
    content:
      "The boy claimed he had never touched a sword.\n\nBut when the ambush began he stepped aside exactly once, at exactly the right angle, as though someone had trained him to survive other people's violence.",
  },
  sword_ch_03: {
    id: "sword_ch_03",
    novelId: "novel_sword",
    title: "Chapter 3 · Wind Over The Shrine",
    order: 3,
    wordCount: 4230,
    updatedAt: "2026-03-19T08:00:00.000Z",
    nav: { previousChapterId: "sword_ch_02", nextChapterId: "sword_ch_04" },
    isFree: true,
    isTrial: false,
    requiresMembership: false,
    isPurchased: true,
    content:
      "The shrine had no priest, only a bell and a sword notch in the oldest cedar.\n\nLu Shen recognized the cut. So did the men following them uphill.",
  },
  sword_ch_04: {
    id: "sword_ch_04",
    novelId: "novel_sword",
    title: "Chapter 4 · Three Schools Waiting",
    order: 4,
    wordCount: 4380,
    updatedAt: "2026-03-20T08:00:00.000Z",
    nav: { previousChapterId: "sword_ch_03", nextChapterId: "sword_ch_05" },
    isFree: true,
    isTrial: false,
    requiresMembership: false,
    isPurchased: true,
    content:
      "Three schools waited on the road and each claimed jurisdiction over justice.\n\nOnly one brought tea.\n\nThat made them the most dangerous.",
  },
  sword_ch_05: {
    id: "sword_ch_05",
    novelId: "novel_sword",
    title: "Chapter 5 · Under The Watchtower",
    order: 5,
    wordCount: 4460,
    updatedAt: "2026-03-21T08:00:00.000Z",
    nav: { previousChapterId: "sword_ch_04" },
    isFree: true,
    isTrial: false,
    requiresMembership: false,
    isPurchased: true,
    content:
      "The tower keeper never asked names.\n\nHe asked who had lied first, which in Lu Shen's experience was another way of asking who would survive the morning.\n\nBelow them, the road lit with torches.",
  },
  orchid_ch_01: {
    id: "orchid_ch_01",
    novelId: "novel_orchid",
    title: "Chapter 1 · Ash In The Warehouse",
    order: 1,
    wordCount: 4670,
    updatedAt: "2026-03-21T08:00:00.000Z",
    nav: { nextChapterId: "orchid_ch_02" },
    isFree: true,
    isTrial: true,
    requiresMembership: false,
    isPurchased: true,
    content:
      "By morning the warehouse had burned so cleanly that the surviving ledger felt planted.\n\nIts orchid stamp belonged to a guild house that closed three seasons ago.\n\nYet the ink on the shipping column was still wet enough to stain her sleeve.",
  },
  orchid_ch_02: {
    id: "orchid_ch_02",
    novelId: "novel_orchid",
    title: "Chapter 2 · Freight Without Witness",
    order: 2,
    wordCount: 4790,
    updatedAt: "2026-03-22T08:00:00.000Z",
    nav: { previousChapterId: "orchid_ch_01", nextChapterId: "orchid_ch_03" },
    isFree: true,
    isTrial: true,
    requiresMembership: false,
    isPurchased: true,
    content:
      "Every freight record on the river had two signatures except the orchid pages.\n\nThose had one seal and no witnesses.\n\nIn a port city, that meant someone expected the river itself to testify.",
  },
  orchid_ch_03: {
    id: "orchid_ch_03",
    novelId: "novel_orchid",
    title: "Chapter 3 · The Missing Seal",
    order: 3,
    wordCount: 4930,
    updatedAt: "2026-03-23T08:00:00.000Z",
    nav: { previousChapterId: "orchid_ch_02" },
    isFree: true,
    isTrial: true,
    requiresMembership: false,
    isPurchased: true,
    content:
      "The seal should have hung from the guild chain wall.\n\nInstead it lay beneath the water stair, wrapped in sailcloth and tied with mourning thread.\n\nWhoever hid it knew the market would search upward first.",
  },
  glass_ch_01: {
    id: "glass_ch_01",
    novelId: "novel_glass",
    title: "Chapter 1 · Customs Bell",
    order: 1,
    wordCount: 4510,
    updatedAt: "2026-03-07T08:00:00.000Z",
    nav: { nextChapterId: "glass_ch_02" },
    isFree: false,
    isTrial: true,
    requiresMembership: true,
    isPurchased: false,
    trialEndOffset: 420,
    content:
      "The customs bell rang three times for a ship no one could see.\n\nAt Glass Harbor, invisible cargo still paid tax.\n\nThat was how Mina learned the weather priests had begun billing absence.",
  },
  glass_ch_02: {
    id: "glass_ch_02",
    novelId: "novel_glass",
    title: "Chapter 2 · Ledger Of Tides",
    order: 2,
    wordCount: 4630,
    updatedAt: "2026-03-08T08:00:00.000Z",
    nav: { previousChapterId: "glass_ch_01", nextChapterId: "glass_ch_03" },
    isFree: false,
    isTrial: true,
    requiresMembership: true,
    isPurchased: false,
    trialEndOffset: 410,
    content:
      "The tide ledger listed imports by storm pattern rather than by captain.\n\nA red mark sat beside tomorrow's rain even though the sky was clear.\n\nSomeone had already sold the weather before it arrived.",
  },
  glass_ch_03: {
    id: "glass_ch_03",
    novelId: "novel_glass",
    title: "Chapter 3 · Tariff For Rain",
    order: 3,
    wordCount: 4760,
    updatedAt: "2026-03-09T08:00:00.000Z",
    nav: { previousChapterId: "glass_ch_02" },
    isFree: false,
    isTrial: false,
    requiresMembership: true,
    isPurchased: false,
    content:
      "By sunset the harbor gates closed against incoming cloud.\n\nCustoms officers stood with dry ledgers while rain waited offshore like unpaid freight.\n\nMina understood then that the city intended to tax the sky itself.",
  },
};
