import { createHash } from "node:crypto";

import { APP_ROUTE_IDS, NOTIFICATION_TYPES } from "@minix/contracts";
import type {
  AccountOperationCooldown,
  AccountOperationKind,
  AccountOperationRecord,
  AccountOperation,
  AuthDeviceIdentity,
  AuthProviderIdentity,
  AuthRateLimitState,
  AuthSecurityAuditEvent,
  AuthSecurityPrompt,
  AuthVerificationPurpose,
  BookshelfItem,
  BookshelfResponse,
  ChapterContent,
  ChapterListResponse,
  ChapterSummary,
  ContentAccess,
  ContentActorRole,
  ContentAttachmentReference,
  ContentAuditEntry,
  ContentAuthoringData,
  ContentCard,
  ContentDetail,
  ContentDetailResponse,
  ContentDisplay,
  ContentLifecycleAction,
  ContentLifecycleMutationRequest,
  ContentLifecycleMutationResponse,
  ContentLifecycle,
  ContentPermissions,
  ContentReviewQueue,
  ContentReviewQueueItem,
  ContentReviewQueueResponse,
  ContentReviewRecord,
  GetContentDetailRequest,
  ListContentReviewQueueRequest,
  SaveContentDraftRequest,
  SaveContentDraftResponse,
  CurrentUserResponse,
  AfterSalesCase,
  AfterSalesDetailResponse,
  AfterSalesListResponse,
  FeedbackBootstrapResponse,
  FeedbackCategory,
  FeedbackFaqEntry,
  FeedbackPriority,
  FeedbackRevisitAction,
  FeedbackRevisitRequest,
  FeedbackRevisitResponse,
  FeedbackTicketActionRequest,
  FeedbackTicketActionResponse,
  FeedbackTicketAssignee,
  FeedbackStatus,
  FeedbackSupportEntry,
  FeedbackTicket,
  FeedbackTicketDetailResponse,
  FeedbackTicketList,
  FeedbackTicketSla,
  FeedbackTicketSummary,
  FeedbackType,
  FeedItem,
  FeedListResponse,
  FeedTag,
  ItemsListResponse,
  ListFeedbackTicketsRequest,
  ListFeedbackTicketsResponse,
  ListUserRelationsRequest,
  MarkNotificationsReadResponse,
  MarkThreadReadRequest,
  MessageConsultationProgress,
  MessageBodyItem,
  MessageDeliveryStatus,
  MessageGroupState,
  MessageReplyPolicy,
  MessageSupportProgress,
  MessageThreadActions,
  MessageThreadList,
  MessageThreadListResponse,
  MessageThreadListSort,
  MessageThreadMember,
  MessageThreadMemberRole,
  MessageThread,
  MessageThreadResponse,
  MessageTouchpoint,
  MessageTouchpointChannel,
  MessageTouchpointProviderMode,
  MessageTouchpointReceipt,
  MessageTouchpointReceiptStatus,
  RetryMessageRequest,
  RetryMessageResponse,
  SyncMessageThreadRequest,
  MembershipOverview,
  MembershipEntitlement,
  NovelCard,
  NovelDetail,
  NovelListResponse,
  NotificationFilterGroup,
  NotificationGroupSummary,
  NotificationItem,
  NotificationList,
  NotificationListResponse,
  NotificationType,
  OrderList,
  OrderListResponse,
  Order,
  OrderDetailResponse,
  OrderSummary,
  ListOrdersRequest,
  PaymentCatalogResponse,
  PaymentCallbackVerification,
  PaymentChannel,
  PaymentGatewayExecutionRequest,
  PaymentGatewayExecutionResponse,
  PaymentGatewayProvider,
  PaymentIntent,
  PaymentLedgerEntry,
  PaymentOperationResult,
  PaymentProduct,
  PaymentProviderMode,
  PaymentReconciliation,
  PaymentReconciliationLedgerEntry,
  PaymentResult,
  PaymentSku,
  ProductBillingCycle,
  ProductType,
  PurchaseOrderRequest,
  PurchaseOrderResponse,
  PurchaseMembershipRequest,
  PurchaseMembershipResponse,
  RelatedNovelSummary,
  SecurityCenter,
  SearchDomain,
  SearchFilterGroup,
  SearchResults,
  SearchSortOption,
  SubscriptionListResponse,
  SubscriptionOperationRequest,
  SubscriptionRecord,
  SubscriptionStatus,
  CreateMessageThreadRequest,
  CreateMessageThreadResponse,
  GetMessageThreadRequest,
  ListUserAssetHistoryRequest,
  SendMessageRequest,
  SendMessageResponse,
  SettingsProfileVisibility,
  SettingsResponse,
  SubmitFeedbackRequest,
  SubmitFeedbackResponse,
  UserAssetHistoryResponse,
  UserAssetSummary,
  UserAssetLedgerEntry,
  UserAvailabilityStatus,
  UserEntitlement,
  UserRelationAction,
  UserRelationList,
  UserRelationListItem,
  UserRelationListKind,
  UserRelationTarget,
  UserFriendState,
  UnreadBadge,
  UploadAsset,
  UploadAttachRequest,
  UploadCancelRequest,
  UploadChunkReceipt,
  UploadChunkRequest,
  UploadCleanupRecord,
  UploadError,
  UploadPipelineSource,
  UploadPipelineRequest,
  UploadPipelineResponse,
  UploadProgress,
  UploadReference,
  UploadReviewRecord,
  UploadRetryRequest,
  UploadReviewStatus,
  UploadScenario,
  UploadSelectionResult,
  UploadSession,
  UploadSessionRequest,
  UploadTask,
  UploadTransferPayload,
} from "@minix/contracts";

import {
  CHAPTER_CONTENT,
  CHAPTER_LISTS,
  DEFAULT_BOOKSHELF_NOVEL_IDS,
  DEFAULT_MEMBERSHIP_OVERVIEW,
  DEFAULT_PROGRESS_BY_NOVEL_ID,
  HOST_ITEMS,
  NOVELS,
} from "./content";
import { createAssetLedgerEntry } from "./domains/account/assets";
import {
  createCurrentUserResponse,
  listUserAssetHistory,
} from "./domains/account/current-user";
import {
  appendAccountOperationRecord,
  clearAccountOperationCooldown,
  createProviderIdentities,
  hasFallbackCredential,
  resolveAccountSecurityPhoneNumber,
  resolveUserAvailability,
  setAccountOperationCooldown,
} from "./domains/account/operations";
import { listUserRelations } from "./domains/account/relations";
import { createDefaultManagedContentEntries } from "./domains/content/managed-content";
import { createMembershipOverview } from "./domains/payment/catalog";
import { resolveSettingsState } from "./domains/settings/state";
import type {
  SessionRecord,
  StoredMessageThreadRecord,
  StoredNotificationTouchpointRecord,
  StoredUploadRecord,
  UserState,
} from "./types";

export { CHAPTER_CONTENT, CHAPTER_LISTS, DEFAULT_MEMBERSHIP_OVERVIEW, NOVELS } from "./content";

export function createDefaultUserState(): UserState {
  return {
    bookshelfNovelIds: new Set(DEFAULT_BOOKSHELF_NOVEL_IDS),
    progressByNovelId: structuredClone(DEFAULT_PROGRESS_BY_NOVEL_ID),
    notificationReadAtById: {},
    threadReadAtById: {},
    threadMessagesByThreadId: {},
    threadRecordsById: {},
    notificationTouchpointReceiptsByNotificationId: {},
    assetLedgerEntries: [
      createAssetLedgerEntry({
        subject: "points",
        kind: "grant",
        title: "Welcome points",
        message: "Initial points granted for the sample account.",
        createdAt: "2026-04-01T08:00:00.000Z",
        sourceType: "system",
        sourceId: "seed_points",
        pointsDelta: 1280,
      }),
      createAssetLedgerEntry({
        subject: "balance",
        kind: "grant",
        title: "Wallet seed",
        message: "Initial wallet balance seeded for sample payment and refund flows.",
        createdAt: "2026-04-01T08:00:00.000Z",
        sourceType: "system",
        sourceId: "seed_balance",
        balanceDeltaCents: 6800,
      }),
      createAssetLedgerEntry({
        subject: "entitlement",
        kind: "expire",
        title: "Expired bonus entitlement",
        message: "A past bonus entitlement expired before the current sample session.",
        createdAt: "2026-03-01T08:00:00.000Z",
        sourceType: "system",
        sourceId: "seed_expired_entitlement",
        entitlement: {
          entitlementId: "ent_bonus_expired",
          key: "bonus-consultation",
          label: "Bonus consultation",
          status: "expired",
          active: false,
          productType: "benefit",
          expiresAt: "2026-03-01T08:00:00.000Z",
        },
      }),
    ],
    operationRecords: [],
    operationCooldownsByKind: {},
    feedbackDetailsById: {},
    feedbackTicketIds: [],
    feedbackFaqCatalog: [],
    feedbackSupportEntries: [],
    ordersById: {},
    orderIdByIdempotencyKey: {},
    afterSalesById: {},
    sharePreparesById: {},
    uploadsByTaskId: {},
    profileOverrides: {
      region: "Shanghai, CN",
      bio: "Sample user profile for shared account-domain integration.",
    },
    relationTarget: {
      targetUserId: "creator_sample",
      displayName: "MiniX Mentor",
      following: true,
      followedBy: true,
      friend: true,
      friendState: "mutual",
      blocked: false,
      remarkName: "MiniX User",
    },
    relationRecordsByUserId: {
      creator_sample: {
        targetUserId: "creator_sample",
        displayName: "MiniX Mentor",
        following: true,
        followedBy: true,
        friend: true,
        friendState: "mutual",
        blocked: false,
        remarkName: "Coach Lin",
        lastInteractionAt: "2026-04-10T08:00:00.000Z",
      },
      practice_buddy: {
        targetUserId: "practice_buddy",
        displayName: "Practice Buddy",
        following: true,
        followedBy: false,
        friend: false,
        friendState: "outgoing_request",
        blocked: false,
        remarkName: "Grammar buddy",
        lastInteractionAt: "2026-04-09T08:00:00.000Z",
      },
      reader_fan: {
        targetUserId: "reader_fan",
        displayName: "Reader Fan",
        following: false,
        followedBy: true,
        friend: false,
        friendState: "incoming_request",
        blocked: false,
        lastInteractionAt: "2026-04-08T08:00:00.000Z",
      },
      review_editor: {
        targetUserId: "review_editor",
        displayName: "Review Editor",
        following: true,
        followedBy: true,
        friend: true,
        friendState: "mutual",
        blocked: false,
        lastInteractionAt: "2026-04-07T08:00:00.000Z",
      },
      noisy_spam: {
        targetUserId: "noisy_spam",
        displayName: "Noisy Spam",
        following: false,
        followedBy: false,
        friend: false,
        friendState: "none",
        blocked: true,
        remarkName: "Muted seller",
        lastInteractionAt: "2026-04-06T08:00:00.000Z",
      },
    },
    managedContentById: createDefaultManagedContentEntries(),
  };
}

export function createSettingsResponse(
  session: SessionRecord,
  userState: UserState,
  deployEnv: string | undefined,
  runtimeEnv?: import("./domains/settings/state").NotificationChannelProviderRuntimeEnv,
): SettingsResponse {
  const settingsState = resolveSettingsState(userState, deployEnv, runtimeEnv);
  const availability = resolveUserAvailability(session, userState);
  const phoneBound = Boolean(session.identity.phoneBound || userState.boundPhoneNumber);
  const wechatBound = userState.wechatBoundOverride ?? Boolean(session.identity.wechatBound);
  const providerCount = createProviderIdentities(session, userState).length;
  return {
    preferences: {
      ...settingsState.preferences,
      theme: session.platform === "wechat" ? "light" : settingsState.preferences.theme,
      account: {
        profileEntryLabel: "Edit profile",
        phoneEntryLabel: phoneBound ? "Change phone" : "Bind phone",
        unbindEntryLabel: wechatBound ? "Unbind WeChat" : "Bind WeChat",
        providerEntryLabel: providerCount > 0 ? `Linked providers (${providerCount})` : "Linked providers",
        cancellationEntryLabel: availability === "cancellation_pending" ? "Cancellation requested" : "Cancellation entry",
      },
    },
    featureToggles: settingsState.featureToggles,
    privacyOptions: settingsState.privacyOptions,
    effectivePolicy: settingsState.effectivePolicy,
    notificationChannels: settingsState.notificationChannels,
    notificationPresets: settingsState.notificationPresets,
    lockedSettingKeys: settingsState.lockedSettingKeys,
  };
}

export function listItems(page = 1, pageSize = 2): ItemsListResponse {
  const start = (page - 1) * pageSize;
  return {
    items: HOST_ITEMS.slice(start, start + pageSize),
    page,
    pageSize,
    hasMore: start + pageSize < HOST_ITEMS.length,
  };
}
